### ISSUE TITLE
[1.19.2] Random crash when entering villages/certain chunks?

### ISSUE THREAD

**Issue by BoardAnims** [SolarMoonQAQ/Spyglass-of-Curios#20] opened 2024-02-02 18:50 UTC
Not even sure if it's this mod thats specifically causing this crash but man I am losing my mind, this custom modpack is causing so many weird errors... If anyone else knows where else i could ask for help for modded scenarios like these, it would be heavily appreciated...

[crash-2024-02-02_18.37.47-server.txt](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/14144037/crash-2024-02-02_18.37.47-server.txt)
[crash-2024-02-01_19.34.52-client.txt](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/14144038/crash-2024-02-01_19.34.52-client.txt)
[crash-2024-02-01_18.39.29-client.txt](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/14144039/crash-2024-02-01_18.39.29-client.txt)
[crash-2024-02-02_19.41.25-server.txt](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/14144040/crash-2024-02-02_19.41.25-server.txt)
Here are multiple logs just incase, a mod might be conflicting with this...

**Comment by SolarMoonQAQ** [comment] 2024-02-03 15:11
Hello friend! It is indeed likely that this issue was caused by this mod, but it should have been fixed in the previously released version 1.7.2. You can try it out to see if the crash still occurs. If there are any problems, I am always here to help you!

**Comment by SolarMoonQAQ** [comment] 2024-02-05 03:33
Closing for now, if you still encounter this problem you can reopen this issue or create a new one at any time.

**Closed as completed by SolarMoonQAQ** 2024-02-05 03:33 UTC
Labels: bug
